import { NextPage } from "next";
import Head from "next/head"
import styles from "./styles.module.scss"
import { SimpleSearchProps } from "../../utils/types";

const SimpleSearch: NextPage<SimpleSearchProps> = ({handleChange, setComplexSearchVisibility}) => {
    return (
    <>
        <Head>
            <title>Simple Search</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.mainPage}>
            {/* <video autoplay loop src="https://www.youtube.com/watch?v=827QFRWNgFw"></video> */}
            <div className={styles.searchContainer}>
                <div className={styles.searchContainer}>
                    <h1>Find your dish!</h1>
                    <input type="text" placeholder="Search for your recipe here!" onChange={handleChange} />
                    <div className={styles.btnContainer}>
                        <button onClick={() => handleSearch(formState.search)}>Search!</button>
                        <button onClick={() => setComplexSearchVisibility(true)}>Expanded Search</button>
                    </div>
                </div>
            </div>
        </main>
    </>
    )
}

export default SimpleSearch